// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type BulkUpsertDocsRequestBody struct {
	// Object key uploaded based on bulk upsert info.
	ObjectKey string `json:"objectKey"`
}

func (b *BulkUpsertDocsRequestBody) GetObjectKey() string {
	if b == nil {
		return ""
	}
	return b.ObjectKey
}

type BulkUpsertDocsRequest struct {
	// Collection name.
	CollectionName string                    `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           BulkUpsertDocsRequestBody `request:"mediaType=application/json"`
}

func (b *BulkUpsertDocsRequest) GetCollectionName() string {
	if b == nil {
		return ""
	}
	return b.CollectionName
}

func (b *BulkUpsertDocsRequest) GetBody() BulkUpsertDocsRequestBody {
	if b == nil {
		return BulkUpsertDocsRequestBody{}
	}
	return b.Body
}

type BulkUpsertDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bulk upsert request accepted.
	MessageResponse *components.MessageResponse
}

func (b BulkUpsertDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkUpsertDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkUpsertDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkUpsertDocsResponse) GetMessageResponse() *components.MessageResponse {
	if b == nil {
		return nil
	}
	return b.MessageResponse
}
