// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type CreateCollectionRequest struct {
	// Collection name must be unique within a project and the supported maximum length is 52.
	CollectionName       string                                  `json:"collectionName"`
	IndexConfigs         map[string]components.IndexConfigsUnion `json:"indexConfigs,omitzero"`
	PartitionConfig      *components.PartitionConfig             `json:"partitionConfig,omitzero"`
	SourceProjectName    *string                                 `json:"sourceProjectName,omitzero"`
	SourceCollectionName *string                                 `json:"sourceCollectionName,omitzero"`
	SourceDatetime       *string                                 `json:"sourceDatetime,omitzero"`
	SourceProjectAPIKey  *string                                 `json:"sourceProjectApiKey,omitzero"`
}

func (c CreateCollectionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCollectionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCollectionRequest) GetCollectionName() string {
	if c == nil {
		return ""
	}
	return c.CollectionName
}

func (c *CreateCollectionRequest) GetIndexConfigs() map[string]components.IndexConfigsUnion {
	if c == nil {
		return nil
	}
	return c.IndexConfigs
}

func (c *CreateCollectionRequest) GetPartitionConfig() *components.PartitionConfig {
	if c == nil {
		return nil
	}
	return c.PartitionConfig
}

func (c *CreateCollectionRequest) GetSourceProjectName() *string {
	if c == nil {
		return nil
	}
	return c.SourceProjectName
}

func (c *CreateCollectionRequest) GetSourceCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.SourceCollectionName
}

func (c *CreateCollectionRequest) GetSourceDatetime() *string {
	if c == nil {
		return nil
	}
	return c.SourceDatetime
}

func (c *CreateCollectionRequest) GetSourceProjectAPIKey() *string {
	if c == nil {
		return nil
	}
	return c.SourceProjectAPIKey
}

// CreateCollectionResponseBody - Created collection
type CreateCollectionResponseBody struct {
	Collection components.CollectionResponse `json:"collection"`
}

func (c *CreateCollectionResponseBody) GetCollection() components.CollectionResponse {
	if c == nil {
		return components.CollectionResponse{}
	}
	return c.Collection
}

type CreateCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created collection
	Object *CreateCollectionResponseBody
}

func (c CreateCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCollectionResponse) GetObject() *CreateCollectionResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
