// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type DeleteCollectionRequest struct {
	// Collection name.
	CollectionName string `pathParam:"style=simple,explode=false,name=collectionName"`
}

func (d *DeleteCollectionRequest) GetCollectionName() string {
	if d == nil {
		return ""
	}
	return d.CollectionName
}

type DeleteCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Collection delete request accepted.
	MessageResponse *components.MessageResponse
}

func (d DeleteCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteCollectionResponse) GetMessageResponse() *components.MessageResponse {
	if d == nil {
		return nil
	}
	return d.MessageResponse
}
