// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type DeleteDocsRequestBody struct {
	// A list of document IDs.
	Ids []string `json:"ids,omitzero"`
	// Query filter.
	Filter          map[string]any              `json:"filter,omitzero"`
	PartitionFilter *components.PartitionFilter `json:"partitionFilter,omitzero"`
}

func (d DeleteDocsRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteDocsRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteDocsRequestBody) GetIds() []string {
	if d == nil {
		return nil
	}
	return d.Ids
}

func (d *DeleteDocsRequestBody) GetFilter() map[string]any {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DeleteDocsRequestBody) GetPartitionFilter() *components.PartitionFilter {
	if d == nil {
		return nil
	}
	return d.PartitionFilter
}

type DeleteDocsRequest struct {
	// Collection name.
	CollectionName string                `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           DeleteDocsRequestBody `request:"mediaType=application/json"`
}

func (d *DeleteDocsRequest) GetCollectionName() string {
	if d == nil {
		return ""
	}
	return d.CollectionName
}

func (d *DeleteDocsRequest) GetBody() DeleteDocsRequestBody {
	if d == nil {
		return DeleteDocsRequestBody{}
	}
	return d.Body
}

type DeleteDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete request accepted.
	MessageResponse *components.MessageResponse
}

func (d DeleteDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteDocsResponse) GetMessageResponse() *components.MessageResponse {
	if d == nil {
		return nil
	}
	return d.MessageResponse
}
