// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type FetchDocsRequestBody struct {
	// A list of document IDs to fetch. Note that the maximum number of document IDs is 100.
	Ids []string `json:"ids"`
	// If your application requires a strongly consistent read, set consistentRead to true. Although a strongly consistent read might take more time than an eventually consistent read, it always returns the last updated value.
	ConsistentRead *bool `default:"false" json:"consistentRead"`
	// If your application need to include vector values in the response, set includeVectors to true.
	IncludeVectors *bool `default:"false" json:"includeVectors"`
	// An object to specify a list of field names to include and/or exclude in the result.
	Fields          *components.FieldsSelectorUnion `json:"fields,omitzero"`
	PartitionFilter *components.PartitionFilter     `json:"partitionFilter,omitzero"`
}

func (f FetchDocsRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchDocsRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchDocsRequestBody) GetIds() []string {
	if f == nil {
		return []string{}
	}
	return f.Ids
}

func (f *FetchDocsRequestBody) GetConsistentRead() *bool {
	if f == nil {
		return nil
	}
	return f.ConsistentRead
}

func (f *FetchDocsRequestBody) GetIncludeVectors() *bool {
	if f == nil {
		return nil
	}
	return f.IncludeVectors
}

func (f *FetchDocsRequestBody) GetFields() *components.FieldsSelectorUnion {
	if f == nil {
		return nil
	}
	return f.Fields
}

func (f *FetchDocsRequestBody) GetPartitionFilter() *components.PartitionFilter {
	if f == nil {
		return nil
	}
	return f.PartitionFilter
}

type FetchDocsRequest struct {
	// Collection name.
	CollectionName string               `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           FetchDocsRequestBody `request:"mediaType=application/json"`
}

func (f *FetchDocsRequest) GetCollectionName() string {
	if f == nil {
		return ""
	}
	return f.CollectionName
}

func (f *FetchDocsRequest) GetBody() FetchDocsRequestBody {
	if f == nil {
		return FetchDocsRequestBody{}
	}
	return f.Body
}

type FetchDocsDoc struct {
	Collection string         `json:"collection"`
	Doc        map[string]any `json:"doc"`
}

func (f *FetchDocsDoc) GetCollection() string {
	if f == nil {
		return ""
	}
	return f.Collection
}

func (f *FetchDocsDoc) GetDoc() map[string]any {
	if f == nil {
		return map[string]any{}
	}
	return f.Doc
}

// FetchDocsResponseBody - Fetched documents.
type FetchDocsResponseBody struct {
	// Total number of documents returned.
	Total int64 `json:"total"`
	// Elapsed time in milliseconds.
	Took int64          `json:"took"`
	Docs []FetchDocsDoc `json:"docs"`
	// Whether the list of documents is included.
	IsDocsInline bool `json:"isDocsInline"`
	// Download URL for the list of documents.
	DocsURL *string `json:"docsUrl,omitzero"`
}

func (f *FetchDocsResponseBody) GetTotal() int64 {
	if f == nil {
		return 0
	}
	return f.Total
}

func (f *FetchDocsResponseBody) GetTook() int64 {
	if f == nil {
		return 0
	}
	return f.Took
}

func (f *FetchDocsResponseBody) GetDocs() []FetchDocsDoc {
	if f == nil {
		return []FetchDocsDoc{}
	}
	return f.Docs
}

func (f *FetchDocsResponseBody) GetIsDocsInline() bool {
	if f == nil {
		return false
	}
	return f.IsDocsInline
}

func (f *FetchDocsResponseBody) GetDocsURL() *string {
	if f == nil {
		return nil
	}
	return f.DocsURL
}

type FetchDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Fetched documents.
	Object *FetchDocsResponseBody
}

func (f FetchDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FetchDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FetchDocsResponse) GetObject() *FetchDocsResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
