// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type GetBulkUpsertDocsRequest struct {
	// Collection name.
	CollectionName string `pathParam:"style=simple,explode=false,name=collectionName"`
}

func (g *GetBulkUpsertDocsRequest) GetCollectionName() string {
	if g == nil {
		return ""
	}
	return g.CollectionName
}

// Type - Content type that must be specified when uploading documents.
type Type string

const (
	TypeApplicationJSON Type = "application/json"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application/json":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// HTTPMethod - HTTP method that must be specified when uploading documents.
type HTTPMethod string

const (
	HTTPMethodPut HTTPMethod = "PUT"
)

func (e HTTPMethod) ToPointer() *HTTPMethod {
	return &e
}
func (e *HTTPMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUT":
		*e = HTTPMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HTTPMethod: %v", v)
	}
}

// GetBulkUpsertDocsResponseBody - Required info to upload documents.
type GetBulkUpsertDocsResponseBody struct {
	// Presigned URL.
	URL string `json:"url"`
	// Content type that must be specified when uploading documents.
	Type *Type `default:"application/json" json:"type"`
	// HTTP method that must be specified when uploading documents.
	HTTPMethod *HTTPMethod `default:"PUT" json:"httpMethod"`
	// Object key that must be specified when uploading documents.
	ObjectKey string `json:"objectKey"`
	// Object size limit in bytes.
	SizeLimitBytes *int64 `default:"209715200" json:"sizeLimitBytes"`
}

func (g GetBulkUpsertDocsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBulkUpsertDocsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetBulkUpsertDocsResponseBody) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

func (g *GetBulkUpsertDocsResponseBody) GetType() *Type {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GetBulkUpsertDocsResponseBody) GetHTTPMethod() *HTTPMethod {
	if g == nil {
		return nil
	}
	return g.HTTPMethod
}

func (g *GetBulkUpsertDocsResponseBody) GetObjectKey() string {
	if g == nil {
		return ""
	}
	return g.ObjectKey
}

func (g *GetBulkUpsertDocsResponseBody) GetSizeLimitBytes() *int64 {
	if g == nil {
		return nil
	}
	return g.SizeLimitBytes
}

type GetBulkUpsertDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Required info to upload documents.
	Object *GetBulkUpsertDocsResponseBody
}

func (g GetBulkUpsertDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBulkUpsertDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetBulkUpsertDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBulkUpsertDocsResponse) GetObject() *GetBulkUpsertDocsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
