// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type GetCollectionRequest struct {
	// Collection name.
	CollectionName string `pathParam:"style=simple,explode=false,name=collectionName"`
}

func (g *GetCollectionRequest) GetCollectionName() string {
	if g == nil {
		return ""
	}
	return g.CollectionName
}

// GetCollectionResponseBody - Describe collection success.
type GetCollectionResponseBody struct {
	Collection components.CollectionResponse `json:"collection"`
}

func (g *GetCollectionResponseBody) GetCollection() components.CollectionResponse {
	if g == nil {
		return components.CollectionResponse{}
	}
	return g.Collection
}

type GetCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Describe collection success.
	Object *GetCollectionResponseBody
}

func (g GetCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCollectionResponse) GetObject() *GetCollectionResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
