// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type ListDocsRequest struct {
	// Collection name.
	CollectionName string `pathParam:"style=simple,explode=false,name=collectionName"`
	// Max number of documents to return at once.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// Next page token.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
}

func (l *ListDocsRequest) GetCollectionName() string {
	if l == nil {
		return ""
	}
	return l.CollectionName
}

func (l *ListDocsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListDocsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

// ListDocsResponseBody - Documents list.
type ListDocsResponseBody struct {
	Total int64 `json:"total"`
	// A list of documents.
	Docs          []map[string]any `json:"docs"`
	NextPageToken *string          `json:"nextPageToken,omitzero"`
}

func (l *ListDocsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListDocsResponseBody) GetDocs() []map[string]any {
	if l == nil {
		return []map[string]any{}
	}
	return l.Docs
}

func (l *ListDocsResponseBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

type ListDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Documents list.
	Object *ListDocsResponseBody
}

func (l ListDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListDocsResponse) GetObject() *ListDocsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
