// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type QueryCollectionRequestBody struct {
	// Number of documents to return. Note that the maximum number of documents is 100.
	Size *int64 `json:"size,omitzero"`
	// Query object.
	Query map[string]any `json:"query"`
	// If your application requires a strongly consistent read, set consistentRead to true. Although a strongly consistent read might take more time than an eventually consistent read, it always returns the last updated value.
	ConsistentRead *bool `default:"false" json:"consistentRead"`
	// If your application need to include vector values in the response, set includeVectors to true.
	IncludeVectors *bool `default:"false" json:"includeVectors"`
	// List of field name, sort direction pairs.
	Sort []map[string]any `json:"sort,omitzero"`
	// An object to specify a list of field names to include and/or exclude in the result.
	Fields          *components.FieldsSelectorUnion `json:"fields,omitzero"`
	PartitionFilter *components.PartitionFilter     `json:"partitionFilter,omitzero"`
}

func (q QueryCollectionRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryCollectionRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryCollectionRequestBody) GetSize() *int64 {
	if q == nil {
		return nil
	}
	return q.Size
}

func (q *QueryCollectionRequestBody) GetQuery() map[string]any {
	if q == nil {
		return map[string]any{}
	}
	return q.Query
}

func (q *QueryCollectionRequestBody) GetConsistentRead() *bool {
	if q == nil {
		return nil
	}
	return q.ConsistentRead
}

func (q *QueryCollectionRequestBody) GetIncludeVectors() *bool {
	if q == nil {
		return nil
	}
	return q.IncludeVectors
}

func (q *QueryCollectionRequestBody) GetSort() []map[string]any {
	if q == nil {
		return nil
	}
	return q.Sort
}

func (q *QueryCollectionRequestBody) GetFields() *components.FieldsSelectorUnion {
	if q == nil {
		return nil
	}
	return q.Fields
}

func (q *QueryCollectionRequestBody) GetPartitionFilter() *components.PartitionFilter {
	if q == nil {
		return nil
	}
	return q.PartitionFilter
}

type QueryCollectionRequest struct {
	// Collection name.
	CollectionName string                     `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           QueryCollectionRequestBody `request:"mediaType=application/json"`
}

func (q *QueryCollectionRequest) GetCollectionName() string {
	if q == nil {
		return ""
	}
	return q.CollectionName
}

func (q *QueryCollectionRequest) GetBody() QueryCollectionRequestBody {
	if q == nil {
		return QueryCollectionRequestBody{}
	}
	return q.Body
}

type QueryCollectionDoc struct {
	// Collection name.
	Collection string `json:"collection"`
	// Document similarity score.
	Score *float64       `json:"score,omitzero"`
	Doc   map[string]any `json:"doc"`
}

func (q *QueryCollectionDoc) GetCollection() string {
	if q == nil {
		return ""
	}
	return q.Collection
}

func (q *QueryCollectionDoc) GetScore() *float64 {
	if q == nil {
		return nil
	}
	return q.Score
}

func (q *QueryCollectionDoc) GetDoc() map[string]any {
	if q == nil {
		return map[string]any{}
	}
	return q.Doc
}

// QueryCollectionResponseBody - Documents selected by query.
type QueryCollectionResponseBody struct {
	// Elapsed time in milliseconds.
	Took int64 `json:"took"`
	// Maximum score.
	MaxScore *float64 `json:"maxScore,omitzero"`
	// Total number of documents returned.
	Total int64 `json:"total"`
	// List of documents.
	Docs []QueryCollectionDoc `json:"docs"`
	// Whether the list of documents is included.
	IsDocsInline bool `json:"isDocsInline"`
	// Optional download URL for the list of documents.
	DocsURL *string `json:"docsUrl,omitzero"`
}

func (q *QueryCollectionResponseBody) GetTook() int64 {
	if q == nil {
		return 0
	}
	return q.Took
}

func (q *QueryCollectionResponseBody) GetMaxScore() *float64 {
	if q == nil {
		return nil
	}
	return q.MaxScore
}

func (q *QueryCollectionResponseBody) GetTotal() int64 {
	if q == nil {
		return 0
	}
	return q.Total
}

func (q *QueryCollectionResponseBody) GetDocs() []QueryCollectionDoc {
	if q == nil {
		return []QueryCollectionDoc{}
	}
	return q.Docs
}

func (q *QueryCollectionResponseBody) GetIsDocsInline() bool {
	if q == nil {
		return false
	}
	return q.IsDocsInline
}

func (q *QueryCollectionResponseBody) GetDocsURL() *string {
	if q == nil {
		return nil
	}
	return q.DocsURL
}

type QueryCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Documents selected by query.
	Object *QueryCollectionResponseBody
}

func (q QueryCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryCollectionResponse) GetObject() *QueryCollectionResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}
