// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type UpdateCollectionRequestBody struct {
	IndexConfigs map[string]components.IndexConfigsUnion `json:"indexConfigs"`
}

func (u *UpdateCollectionRequestBody) GetIndexConfigs() map[string]components.IndexConfigsUnion {
	if u == nil {
		return map[string]components.IndexConfigsUnion{}
	}
	return u.IndexConfigs
}

type UpdateCollectionRequest struct {
	// Collection name.
	CollectionName string                      `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           UpdateCollectionRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateCollectionRequest) GetCollectionName() string {
	if u == nil {
		return ""
	}
	return u.CollectionName
}

func (u *UpdateCollectionRequest) GetBody() UpdateCollectionRequestBody {
	if u == nil {
		return UpdateCollectionRequestBody{}
	}
	return u.Body
}

// UpdateCollectionResponseBody - Updated collection
type UpdateCollectionResponseBody struct {
	Collection components.CollectionResponse `json:"collection"`
}

func (u *UpdateCollectionResponseBody) GetCollection() components.CollectionResponse {
	if u == nil {
		return components.CollectionResponse{}
	}
	return u.Collection
}

type UpdateCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated collection
	Object *UpdateCollectionResponseBody
}

func (u UpdateCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCollectionResponse) GetObject() *UpdateCollectionResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
