// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type UpdateDocsRequestBody struct {
	// A list of documents to update. Each document must contain 'id' field to be updated.
	Docs []map[string]any `json:"docs"`
}

func (u *UpdateDocsRequestBody) GetDocs() []map[string]any {
	if u == nil {
		return []map[string]any{}
	}
	return u.Docs
}

type UpdateDocsRequest struct {
	// Collection name.
	CollectionName string                `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           UpdateDocsRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateDocsRequest) GetCollectionName() string {
	if u == nil {
		return ""
	}
	return u.CollectionName
}

func (u *UpdateDocsRequest) GetBody() UpdateDocsRequestBody {
	if u == nil {
		return UpdateDocsRequestBody{}
	}
	return u.Body
}

type UpdateDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update request accepted.
	MessageResponse *components.MessageResponse
}

func (u UpdateDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateDocsResponse) GetMessageResponse() *components.MessageResponse {
	if u == nil {
		return nil
	}
	return u.MessageResponse
}
