// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lambdadb/go-lambdadb/internal/utils"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type UpsertDocsRequestBody struct {
	// A list of documents to upsert.
	Docs []map[string]any `json:"docs"`
}

func (u *UpsertDocsRequestBody) GetDocs() []map[string]any {
	if u == nil {
		return []map[string]any{}
	}
	return u.Docs
}

type UpsertDocsRequest struct {
	// Collection name.
	CollectionName string                `pathParam:"style=simple,explode=false,name=collectionName"`
	Body           UpsertDocsRequestBody `request:"mediaType=application/json"`
}

func (u *UpsertDocsRequest) GetCollectionName() string {
	if u == nil {
		return ""
	}
	return u.CollectionName
}

func (u *UpsertDocsRequest) GetBody() UpsertDocsRequestBody {
	if u == nil {
		return UpsertDocsRequestBody{}
	}
	return u.Body
}

type UpsertDocsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Upsert request accepted.
	MessageResponse *components.MessageResponse
}

func (u UpsertDocsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertDocsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpsertDocsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpsertDocsResponse) GetMessageResponse() *components.MessageResponse {
	if u == nil {
		return nil
	}
	return u.MessageResponse
}
