// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/lambdadb/go-lambdadb/internal/utils"
)

type FieldsSelector2 struct {
	// List of field names to include in the result.
	Include []string `json:"include,omitzero"`
	// List of field names to exclude in the result.
	Exclude []string `json:"exclude"`
}

func (f FieldsSelector2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FieldsSelector2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FieldsSelector2) GetInclude() []string {
	if f == nil {
		return nil
	}
	return f.Include
}

func (f *FieldsSelector2) GetExclude() []string {
	if f == nil {
		return []string{}
	}
	return f.Exclude
}

type FieldsSelector1 struct {
	// List of field names to include in the result.
	Include []string `json:"include"`
	// List of field names to exclude in the result.
	Exclude []string `json:"exclude,omitzero"`
}

func (f FieldsSelector1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FieldsSelector1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FieldsSelector1) GetInclude() []string {
	if f == nil {
		return []string{}
	}
	return f.Include
}

func (f *FieldsSelector1) GetExclude() []string {
	if f == nil {
		return nil
	}
	return f.Exclude
}

type FieldsSelectorUnionType string

const (
	FieldsSelectorUnionTypeFieldsSelector1 FieldsSelectorUnionType = "FieldsSelector_1"
	FieldsSelectorUnionTypeFieldsSelector2 FieldsSelectorUnionType = "FieldsSelector_2"
)

// FieldsSelectorUnion - An object to specify a list of field names to include and/or exclude in the result.
type FieldsSelectorUnion struct {
	FieldsSelector1 *FieldsSelector1 `queryParam:"inline" union:"member"`
	FieldsSelector2 *FieldsSelector2 `queryParam:"inline" union:"member"`

	Type FieldsSelectorUnionType
}

func CreateFieldsSelectorUnionFieldsSelector1(fieldsSelector1 FieldsSelector1) FieldsSelectorUnion {
	typ := FieldsSelectorUnionTypeFieldsSelector1

	return FieldsSelectorUnion{
		FieldsSelector1: &fieldsSelector1,
		Type:            typ,
	}
}

func CreateFieldsSelectorUnionFieldsSelector2(fieldsSelector2 FieldsSelector2) FieldsSelectorUnion {
	typ := FieldsSelectorUnionTypeFieldsSelector2

	return FieldsSelectorUnion{
		FieldsSelector2: &fieldsSelector2,
		Type:            typ,
	}
}

func (u *FieldsSelectorUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var fieldsSelector1 FieldsSelector1 = FieldsSelector1{}
	if err := utils.UnmarshalJSON(data, &fieldsSelector1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FieldsSelectorUnionTypeFieldsSelector1,
			Value: &fieldsSelector1,
		})
	}

	var fieldsSelector2 FieldsSelector2 = FieldsSelector2{}
	if err := utils.UnmarshalJSON(data, &fieldsSelector2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FieldsSelectorUnionTypeFieldsSelector2,
			Value: &fieldsSelector2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FieldsSelectorUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FieldsSelectorUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FieldsSelectorUnionType)
	switch best.Type {
	case FieldsSelectorUnionTypeFieldsSelector1:
		u.FieldsSelector1 = best.Value.(*FieldsSelector1)
		return nil
	case FieldsSelectorUnionTypeFieldsSelector2:
		u.FieldsSelector2 = best.Value.(*FieldsSelector2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FieldsSelectorUnion", string(data))
}

func (u FieldsSelectorUnion) MarshalJSON() ([]byte, error) {
	if u.FieldsSelector1 != nil {
		return utils.MarshalJSON(u.FieldsSelector1, "", true)
	}

	if u.FieldsSelector2 != nil {
		return utils.MarshalJSON(u.FieldsSelector2, "", true)
	}

	return nil, errors.New("could not marshal union type FieldsSelectorUnion: all fields are null")
}
