// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MessageResponse struct {
	Message string `json:"message"`
}

func (m *MessageResponse) GetMessage() string {
	if m == nil {
		return ""
	}
	return m.Message
}
