// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DataType - Partition field data type.
type DataType string

const (
	DataTypeKeyword DataType = "keyword"
)

func (e DataType) ToPointer() *DataType {
	return &e
}
func (e *DataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "keyword":
		*e = DataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DataType: %v", v)
	}
}

type PartitionConfig struct {
	// Partition field name.
	FieldName *string `json:"fieldName,omitzero"`
	// Partition field data type.
	DataType *DataType `json:"dataType,omitzero"`
	// The number of partitions.
	NumPartitions *int64 `json:"numPartitions,omitzero"`
}

func (p *PartitionConfig) GetFieldName() *string {
	if p == nil {
		return nil
	}
	return p.FieldName
}

func (p *PartitionConfig) GetDataType() *DataType {
	if p == nil {
		return nil
	}
	return p.DataType
}

func (p *PartitionConfig) GetNumPartitions() *int64 {
	if p == nil {
		return nil
	}
	return p.NumPartitions
}
