// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PartitionFilter struct {
	// Partition field name.
	Field string `json:"field"`
	// Partition values to filter.
	In []string `json:"in"`
}

func (p *PartitionFilter) GetField() string {
	if p == nil {
		return ""
	}
	return p.Field
}

func (p *PartitionFilter) GetIn() []string {
	if p == nil {
		return []string{}
	}
	return p.In
}
