// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	ProjectAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=x-api-key,env=lambdadb_project_api_key"`
}

func (s *Security) GetProjectAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.ProjectAPIKey
}
