// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Status
type Status string

const (
	StatusCreating Status = "CREATING"
	StatusActive   Status = "ACTIVE"
	StatusDeleting Status = "DELETING"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "CREATING", "ACTIVE", "DELETING":
			return true
		}
	}
	return false
}
