// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/lambdadb/go-lambdadb/models/components"
)

type ResourceAlreadyExistsError struct {
	Message  *string                 `json:"message,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ResourceAlreadyExistsError{}

func (e *ResourceAlreadyExistsError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
